---
- name: Scan network for open ports
  hosts: localhost
  tasks:
  - name: Scan network
    community.general.nmap:
      scan_type: SYN
      target: 172.31.0.0/28
    register: scan_result
  - debug:
      var: scan_result
